<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.agoncal.application</groupId>
  <artifactId>petstoreee7</artifactId>
  <version>7.0</version>
  <packaging>war</packaging>
  <name>Petstore application using Java EE 7</name>

  <properties>
    <!-- Java EE and App servers -->
    <version.javaee>7.0</version.javaee>
    <version.jboss-javaee>1.1.1.Final</version.jboss-javaee>
    <version.wildfly>26.1.3.Final</version.wildfly>
    <!-- Test -->
    <version.junit>4.13.2</version.junit>
    <version.arquillian>1.5.0.0</version.arquillian>
    <version.arquillian.wildfly>3.0.1.Final</version.arquillian.wildfly>
    <version.shrinkwrap>1.2.6</version.shrinkwrap>
    <version.arquillian.rest>1.0.0.Alpha4</version.arquillian.rest>
    <version.resteasy>6.2.12.Final</version.resteasy>
    <version.derby>10.10.1.1</version.derby>
    <version.equalsverifier>3.19.3</version.equalsverifier>
    <!-- UI (WebJar, Bootstrap, JQuery...) -->
    <version.bootstrap>5.3.5</version.bootstrap>
    <version.jquery>3.7.1</version.jquery>
    <version.primefaces>15.0.3</version.primefaces>
    <version.primefaces-themes>1.1.0</version.primefaces-themes>
    <version.fontawesome>4.7.0</version.fontawesome>
    <!-- Other -->
    <version.swagger>1.6.9</version.swagger>
    <version.log4j>2.25.2</version.log4j>
    <!--Maven Plugins & co-->
    <version.maven.wildfly.plugin>5.1.3.Final</version.maven.wildfly.plugin>
    <version.maven.war.plugin>3.4.0</version.maven.war.plugin>
    <version.maven.compiler.plugin>3.1</version.maven.compiler.plugin>
    <version.maven.dependency.plugin>3.8.1</version.maven.dependency.plugin>
    <skipITs>true</skipITs>
    <version.maven.surefire.plugin>3.5.3</version.maven.surefire.plugin>
    <version.maven.failsafe.plugin>3.1.2</version.maven.failsafe.plugin>
    <version.swagger.plugin>3.1.8</version.swagger.plugin>
    <!-- Project -->
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <maven.compiler.release>21</maven.compiler.release>
  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- App servers -->
      <dependency>
        <groupId>org.jboss.spec</groupId>
        <artifactId>jboss-javaee-7.0</artifactId>
        <version>${version.jboss-javaee}</version>
        <type>pom</type>
        <scope>provided</scope>
      </dependency>
      <!-- Test -->
      <dependency>
        <groupId>org.arquillian</groupId>
        <artifactId>arquillian-universe</artifactId>
        <version>${version.arquillian}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>${version.junit}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.jboss.resteasy</groupId>
        <artifactId>resteasy-client</artifactId>
        <version>${version.resteasy}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>nl.jqno.equalsverifier</groupId>
        <artifactId>equalsverifier</artifactId>
        <version>${version.equalsverifier}</version>
        <scope>test</scope>
      </dependency>
      <!-- UI (WebJar, Bootstrap, JQuery...) -->
      <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>bootstrap</artifactId>
        <version>${version.bootstrap}</version>
      </dependency>
      <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>jquery</artifactId>
        <version>${version.jquery}</version>
      </dependency>
      <dependency>
        <groupId>org.primefaces</groupId>
        <artifactId>primefaces</artifactId>
        <version>${version.primefaces}</version>
      </dependency>
      <dependency>
        <groupId>org.primefaces.themes</groupId>
        <artifactId>all-themes</artifactId>
        <version>${version.primefaces-themes}</version>
      </dependency>
      <dependency>
        <groupId>org.webjars.bower</groupId>
        <artifactId>fontawesome</artifactId>
        <version>${version.fontawesome}</version>
      </dependency>
      <!-- Other -->
      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>2.24.3</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-annotations</artifactId>
      <version>2.2.40</version>
    </dependency>
    <dependency>
      <groupId>jakarta.inject</groupId>
      <artifactId>jakarta.inject-api</artifactId>
      <version>2.0.1</version>
    </dependency>
    <dependency>
      <groupId>jakarta.ejb</groupId>
      <artifactId>jakarta.ejb-api</artifactId>
      <version>4.0.1</version>
    </dependency>
    <dependency>
      <groupId>jakarta.enterprise</groupId>
      <artifactId>jakarta.enterprise.cdi-api</artifactId>
      <version>4.1.0</version>
    </dependency>
    <dependency>
      <groupId>jakarta.faces</groupId>
      <artifactId>jakarta.faces-api</artifactId>
      <version>4.1.2</version>
    </dependency>
    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.interceptor</groupId>
      <artifactId>jakarta.interceptor-api</artifactId>
      <version>2.2.0</version>
    </dependency>
    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
      <version>3.2.0</version>
    </dependency>
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
      <version>3.1.1</version>
    </dependency>
    <dependency>
      <groupId>jakarta.ws.rs</groupId>
      <artifactId>jakarta.ws.rs-api</artifactId>
      <version>4.0.0</version>
    </dependency>
    <dependency>
      <groupId>jakarta.xml.bind</groupId>
      <artifactId>jakarta.xml.bind-api</artifactId>
      <version>4.0.4</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>bootstrap</artifactId>
    </dependency>
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>jquery</artifactId>
    </dependency>
    <dependency>
      <groupId>org.primefaces</groupId>
      <artifactId>primefaces</artifactId>
      <version>${version.primefaces}</version>
      <classifier>jakarta</classifier>
    </dependency>
    <dependency>
      <groupId>org.primefaces.themes</groupId>
      <artifactId>all-themes</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
      <version>3.4.5</version>
    </dependency>
    <dependency>
      <groupId>org.webjars.bower</groupId>
      <artifactId>fontawesome</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jboss.spec</groupId>
      <artifactId>jboss-javaee-7.0</artifactId>
      <type>pom</type>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>4.0.6</version>
      <scope>runtime</scope>
    </dependency>
    <!-- TEST -->
    <dependency>
      <groupId>nl.jqno.equalsverifier</groupId>
      <artifactId>equalsverifier</artifactId>
    </dependency>
    <dependency>
      <groupId>org.arquillian.universe</groupId>
      <artifactId>arquillian-junit</artifactId>
      <scope>test</scope>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>org.jboss.shrinkwrap</groupId>
      <artifactId>shrinkwrap-api</artifactId>
      <version>${version.shrinkwrap}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.14.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.extension</groupId>
      <artifactId>arquillian-rest-client-api</artifactId>
      <version>${version.arquillian.rest}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.extension</groupId>
      <artifactId>arquillian-rest-client-impl-3x</artifactId>
      <version>${version.arquillian.rest}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-jackson-provider</artifactId>
      <version>3.15.6.Final</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <finalName>applicationPetstore</finalName>
    <plugins>
      <plugin>
        <groupId>org.wildfly.plugins</groupId>
        <artifactId>wildfly-maven-plugin</artifactId>
        <version>${version.maven.wildfly.plugin}</version>
      </plugin>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>${version.maven.war.plugin}</version>
        <configuration>
          <failOnMissingWebXml>false</failOnMissingWebXml>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${version.maven.surefire.plugin}</version>
      </plugin>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>3.5.3</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.github.kongchen</groupId>
        <artifactId>swagger-maven-plugin</artifactId>
        <version>${version.swagger.plugin}</version>
        <configuration>
          <apiSources>
            <apiSource>
              <springmvc>false</springmvc>
              <locations>org.agoncal.application.petstore.rest</locations>
              <schemes>http,https</schemes>
              <host>localhost:8080</host>
              <basePath>/applicationPetstore/rest</basePath>
              <outputFormats>json</outputFormats>
              <info>
                <title>Petstore APIs</title>
                <version>1.0.0</version>
                <description>PetStore APIs exposed</description>
                <contact>
                  <email>antonio.goncalves@gmail.com</email>
                  <name>Antonio Goncalves</name>
                  <url>https://antoniogoncalves.org/</url>
                </contact>
              </info>
              <swaggerDirectory>${basedir}/src/main/webapp</swaggerDirectory>
              <attachSwaggerArtifact>true</attachSwaggerArtifact>
            </apiSource>
          </apiSources>
        </configuration>
        <executions>
          <execution>
            <phase>compile</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-hibernate-validations</artifactId>
            <version>${version.swagger}</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>arquillian-wildfly-remote</id>
      <properties>
        <skipITs>false</skipITs>
      </properties>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>3.1.2</version>
            <configuration>
              <systemPropertyVariables>
                <arquillian.launch>arquillian-wildfly-remote</arquillian.launch>
              </systemPropertyVariables>
            </configuration>
          </plugin>
        </plugins>
      </build>
      <dependencies>
        <dependency>
          <groupId>org.wildfly.arquillian</groupId>
          <artifactId>wildfly-arquillian-container-remote</artifactId>
          <version>${version.arquillian.wildfly}</version>
          <scope>test</scope>
        </dependency>
      </dependencies>
    </profile>

    <profile>
      <id>arquillian-wildfly-managed</id>
      <properties>
        <skipITs>false</skipITs>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>${version.maven.dependency.plugin}</version>
            <executions>
              <execution>
                <id>unpack</id>
                <phase>process-test-classes</phase>
                <goals>
                  <goal>unpack</goal>
                </goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.wildfly</groupId>
                      <artifactId>wildfly-dist</artifactId>
                      <version>${version.wildfly}</version>
                      <type>zip</type>
                      <overWrite>false</overWrite>
                      <!-- TODO don't know why but the plugin looks for a directory called wildfly-11.0.0.Final and not wildfly-${version.wildfly} -->
                      <outputDirectory>${project.build.directory}/wildfly-11.0.0.Final</outputDirectory>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>3.1.2</version>
            <configuration>
              <skipTests>false</skipTests>
              <systemPropertyVariables>
                <arquillian.launch>arquillian-wildfly-managed</arquillian.launch>
                <jboss.home>${project.build.directory}/wildfly-${version.wildfly}</jboss.home>
              </systemPropertyVariables>
            </configuration>
          </plugin>
        </plugins>
      </build>
      <dependencies>
        <dependency>
          <groupId>org.wildfly.arquillian</groupId>
          <artifactId>wildfly-arquillian-container-managed</artifactId>
          <version>${version.arquillian.wildfly}</version>
          <scope>test</scope>
        </dependency>
      </dependencies>
    </profile>
  </profiles>


  <repositories>
    <!--Q Developer Agent for Code Transformation has added a repository dependency from MavenCentral to download the newly upgraded dependencies as part of the transformation process-->
    <repository>
      <id>QCT-MavenCentral-Access</id>
      <name>Maven Central</name>
      <layout>default</layout>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
    <!--Please add the following dependency to your internal repositories, remove or replace this block with your internal repository or mirror, if you do NOT want access to MavenCentral by default-->
    <repository>
      <id>primefaces</id>
      <url>https://repository.primefaces.org/</url>
    </repository>
  </repositories>

</project>
